FROM postgres:alpine

# Set environment variables for the default user, password, and database
# of course in a real project I would hide these with real env variables etc
ENV POSTGRES_USER=veesion
ENV POSTGRES_PASSWORD=secret
ENV POSTGRES_DB=veesion
